export const DAILY_GAME_ACTIONS = {
  FETCH_DAILY_GAMES: 'FETCH_DAILY_GAMES',
  FETCH_DAILY_GAMES_SUCCESS: 'FETCH_DAILY_GAMES_SUCCESS',
  FETCH_DAILY_GAMES_FAILURE: 'FETCH_DAILY_GAMES_FAILURE',
};

export const getGames = (date) => ({
    type: DAILY_GAME_ACTIONS.FETCH_DAILY_GAMES,
    payload: date,
});
